ALTER TABLE "Place" ADD COLUMN IF NOT EXISTS "faqItems" JSONB;
ALTER TABLE "PlaceRevision" ADD COLUMN IF NOT EXISTS "faqItems" JSONB;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "faqItems" JSONB;
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "faqItems" JSONB;
