export const PASSWORD_RESET_TOKEN_TTL_MS = 60 * 60 * 1000;

export const PASSWORD_RESET_RESEND_COOLDOWN_SECONDS = 60;

export const PASSWORD_RESET_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;

export const PASSWORD_RESET_RATE_LIMIT_MAX = 3;
