/**
 * Discovery Signal Types
 *
 * This module defines the type system for discovery signals.
 * Signals are normalized, ranking-quality representations of user interactions.
 *
 * Key distinction:
 * - UserEvent: Raw, immutable telemetry (what happened)
 * - DiscoverySignal: Normalized ranking signal (what it means for discovery)
 */

import type {
  DiscoverySignalType,
  SignalCategory,
} from './discoverySignalWeights';
import { DISCOVERY_SIGNAL_WEIGHTS } from './discoverySignalWeights';

/**
 * A discovery signal represents a user interaction normalized for ranking purposes.
 * Signals are immutable and carry semantic meaning for discovery intelligence.
 */
export interface DiscoverySignal {
  /** The type of signal (e.g., BOOKING_COMPLETED) */
  type: DiscoverySignalType;

  /** The entity this signal is about (e.g., placeId, offerId) */
  entityId: string;

  /** The entity type (place, offer, event, etc.) */
  entityType: 'place' | 'offer' | 'event';

  /** The user who generated this signal */
  userId: string;

  /** When this signal was generated */
  timestamp: Date;

  /** The weight of this signal for ranking purposes */
  weight: number;

  /** Optional context about the signal */
  context?: {
    /** For booking signals: the booking ID */
    bookingId?: string;
    /** For feedback signals: the feedback ID */
    feedbackId?: string;
    /** For plan signals: the plan ID */
    planId?: string;
    /** Additional metadata */
    metadata?: Record<string, unknown>;
  };
}

/**
 * High-intent signals indicate strong user interest
 * These are signals that suggest the user is seriously considering an action
 */
export type HighIntentSignal = Extract<
  DiscoverySignalType,
  'SAVE' | 'PLAN_ADD' | 'CTA_CLICK'
>;

/**
 * Conversion signals indicate completed transactions or strong commitments
 * These are the strongest indicators of user satisfaction and intent
 */
export type ConversionSignal = Extract<
  DiscoverySignalType,
  'BOOKING_CREATED' | 'BOOKING_CONFIRMED' | 'BOOKING_COMPLETED' | 'FEEDBACK_LEFT'
>;

/**
 * Signal weight map for type-safe access
 */
export type SignalWeightMap = typeof DISCOVERY_SIGNAL_WEIGHTS;

/**
 * Aggregated signal metrics for an entity
 * Used for future discovery scoring and ranking
 */
export interface EntitySignalMetrics {
  /** The entity being measured */
  entityId: string;
  entityType: 'place' | 'offer' | 'event';

  /** Total signal weight across all users */
  totalWeight: number;

  /** Count of unique users who generated signals */
  uniqueUsers: number;

  /** Breakdown by signal category */
  byCategory: Partial<Record<SignalCategory, number>>;

  /** Breakdown by signal type */
  byType: Partial<Record<DiscoverySignalType, number>>;

  /** When these metrics were last updated */
  lastUpdated: Date;
}

/**
 * User signal profile for personalization
 * Represents a user's signal generation patterns
 */
export interface UserSignalProfile {
  userId: string;

  /** Total signals generated by this user */
  totalSignals: number;

  /** Distribution of signals by category */
  categoryDistribution: Partial<Record<SignalCategory, number>>;

  /** Average weight of signals generated */
  averageSignalWeight: number;

  /** User's signal generation intensity (signals per day) */
  signalIntensity: number;

  /** When this profile was last updated */
  lastUpdated: Date;
}
