version: "3.9"
services:
  db:
    image: postgres:16
    container_name: mamago2-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mamago
      POSTGRES_PASSWORD: mamago
      POSTGRES_DB: mamago2
    ports:
      - "5433:5432"
    volumes:
      - mamago2_pg:/var/lib/postgresql/data

volumes:
  mamago2_pg:
