import type { NextConfig } from "next";
import { withSentryConfig } from "@sentry/nextjs";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const defaultDevOrigins = [
  "http://localhost:3000",
  "http://127.0.0.1:3000",
  "http://mamago.local:3000",
  "http://admin.mamago.local:3000",
  "http://business.mamago.local:3000",
  "http://192.168.0.106:3000",
  "localhost:3000",
  "127.0.0.1:3000",
  "mamago.local:3000",
  "admin.mamago.local:3000",
  "business.mamago.local:3000",
  "192.168.0.106:3000",
  "192.168.0.106",
  "mamago.local",
  "admin.mamago.local",
  "business.mamago.local",
];

const envDevOrigins = (process.env.NEXT_DEV_ALLOWED_ORIGINS ?? "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);

const allowedDevOrigins = Array.from(
  new Set([...defaultDevOrigins, ...envDevOrigins]),
);

/** Minimal RFC-4180 CSV line splitter (handles quoted fields with embedded commas). */
function csvSplitLine(line: string): string[] {
  const fields: string[] = [];
  let i = 0;
  while (i <= line.length) {
    if (line[i] === '"') {
      let j = i + 1;
      while (j < line.length) {
        if (line[j] === '"' && line[j + 1] === '"') { j += 2; continue; }
        if (line[j] === '"') break;
        j++;
      }
      fields.push(line.slice(i + 1, j).replace(/""/g, '"'));
      i = j + 2; // skip closing quote + comma
    } else {
      const end = line.indexOf(",", i);
      if (end === -1) { fields.push(line.slice(i)); break; }
      fields.push(line.slice(i, end));
      i = end + 1;
    }
  }
  return fields;
}

/**
 * Reads manifest.csv (generated by `pnpm build-migration-manifest`) and
 * returns Next.js redirect rules for wp_journal and slug_history rows.
 *
 * Only rows with a non-empty old_url and new_url are included.
 * Targets are path-only (base URL stripped) to match Next.js redirect format.
 * All redirects are permanent (301) — canonical URL migration, no rollback.
 */
function loadManifestRedirects(): Array<{ source: string; destination: string; permanent: boolean }> {
  const manifestPath = join(process.cwd(), "manifest.csv");
  if (!existsSync(manifestPath)) return [];

  const lines = readFileSync(manifestPath, "utf8").trim().split("\n");
  const [header, ...rows] = lines;
  const cols = header.split(",");
  const idx = (name: string) => cols.indexOf(name);

  const redirects: Array<{ source: string; destination: string; permanent: boolean }> = [];

  for (const raw of rows) {
    const cells = csvSplitLine(raw);

    const ruleType = cells[idx("rule_type")] ?? "";
    const oldUrl  = cells[idx("old_url")]   ?? "";
    const newUrl  = cells[idx("new_url")]   ?? "";

    if (!["wp_journal", "slug_history"].includes(ruleType)) continue;
    if (!oldUrl || !newUrl) continue;

    // Strip the absolute base so Next.js gets path-only source/destination.
    const toPath = (url: string) => {
      try { return new URL(url).pathname; } catch { return url; }
    };

    const source      = toPath(oldUrl);
    const destination = toPath(newUrl);

    // Guard: destination must not end with a slash (no-trailing-slash policy).
    if (destination.endsWith("/") && destination !== "/") {
      console.warn(`[manifest] Skipping redirect with trailing slash target: ${destination}`);
      continue;
    }

    redirects.push({ source, destination, permanent: true });
  }

  return redirects;
}

const nextConfig: NextConfig = {
  /* config options here */
  // No-trailing-slash policy: canonical URLs never end with `/`.
  // Incoming requests with a trailing slash are redirected (301) by middleware.
  trailingSlash: false,

  // В dev React Compiler сильно раздувает время компиляции страниц (десятки секунд TTFB).
  // В production оставляем включённым.
  reactCompiler: process.env.NODE_ENV === "production",

  // Standalone output для Docker-сборки
  output: "standalone",

  async redirects() {
    const manifestRedirects = loadManifestRedirects();
    return [
      // Static legacy redirects (pre-mamaGo 2.0 paths)
      { source: "/birthday", destination: "/minsk/birthday/make", permanent: true },
      { source: "/birthday/builder", destination: "/minsk/birthday/make", permanent: true },
      // SEO migration: wp_journal + slug_history from manifest.csv
      // Regenerate: pnpm build-migration-manifest → pnpm build
      ...manifestRedirects,
    ];
  },

  // Exclude sharp from client bundle (server-only image processing)
  serverExternalPackages: ['sharp'],

  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
      {
        protocol: "https",
        hostname: "**.unsplash.com",
      },
      {
        protocol: "https",
        hostname: "family.by",
      },
      {
        protocol: "https",
        hostname: "**.googleusercontent.com",
      },
    ],
  },

  experimental: {
    // Set body size limit for API routes (10MB for image uploads)
    serverActions: {
      bodySizeLimit: '10mb',
    },
  },

  /** Доступ к dev с localhost / кастомного local-domain / LAN без поломанной загрузки `/_next/*`. */
  allowedDevOrigins,
};

export default withSentryConfig(nextConfig, {
  // For all available options, see:
  // https://github.com/getsentry/sentry-webpack-plugin#options

  org: "mamago",
  project: "mamago2",

  // Only print logs for uploading source maps in CI
  silent: !process.env.CI,

  // For all available options, see:
  // https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/

  // Upload a larger set of source maps for better stack traces (increases build time)
  widenClientFileUpload: true,

  // Automatically annotate React components to show their full name in breadcrumbs and error reports
  reactComponentAnnotation: {
    enabled: true,
  },

  // Route browser requests to Sentry through a Next.js rewrite to circumvent ad-blockers.
  // This can increase your server load as well as your Sentry bill.
  tunnelRoute: "/monitoring",

  // Automatically tree-shake Sentry logger statements to reduce bundle size
  disableLogger: true,

  // Enables automatic instrumentation of Vercel Cron Monitors. (Does not yet work with App Router route handlers.)
  // See the following for more information:
  // https://docs.sentry.io/product/crons/
  // https://vercel.com/docs/cron-jobs
  automaticVercelMonitors: true,
});
