"use client";

import { useState } from "react";
import { Edit2, Check, X, Sparkles } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

interface MediaMetadataEditorProps {
  mediaId: string;
  alt?: string | null;
  title?: string | null;
  caption?: string | null;
  autoGeneratedAlt?: string;
  autoGeneratedTitle?: string;
  autoGeneratedCaption?: string;
  onUpdate?: () => void;
}

export function MediaMetadataEditor({
  mediaId,
  alt,
  title,
  caption,
  autoGeneratedAlt,
  autoGeneratedTitle,
  autoGeneratedCaption,
  onUpdate,
}: MediaMetadataEditorProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [formData, setFormData] = useState({
    alt: alt || "",
    title: title || "",
    caption: caption || "",
  });

  const handleSave = async () => {
    setIsSaving(true);
    setError(null);

    try {
      const response = await fetch(`/api/admin/media/${mediaId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          alt: formData.alt || null,
          title: formData.title || null,
          caption: formData.caption || null,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to update");
      }

      setIsEditing(false);
      onUpdate?.();
      window.location.reload();
    } catch (err) {
      setError("Ошибка сохранения");
    } finally {
      setIsSaving(false);
    }
  };

  const handleAutoFill = () => {
    setFormData({
      alt: autoGeneratedAlt || formData.alt,
      title: autoGeneratedTitle || formData.title,
      caption: autoGeneratedCaption || formData.caption,
    });
  };

  if (!isEditing) {
    return (
      <div className="bg-white rounded-lg shadow p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-gray-900">Метаданные</h2>
          <button
            onClick={() => setIsEditing(true)}
            className="inline-flex items-center gap-2 px-3 py-1.5 text-sm text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition-colors"
          >
            <Edit2 className="w-4 h-4" />
            Редактировать
          </button>
        </div>
        
        <dl className="space-y-4">
          <div>
            <dt className="text-sm font-medium text-gray-500 mb-1">Заголовок</dt>
            <dd className="text-sm text-gray-900">
              {title || autoGeneratedTitle || (
                <span className="text-gray-400 italic">Не указан</span>
              )}
            </dd>
          </div>
          
          <div>
            <dt className="text-sm font-medium text-gray-500 mb-1">Alt текст</dt>
            <dd className="text-sm text-gray-900">
              {alt || autoGeneratedAlt || (
                <span className="text-gray-400 italic">Не указан</span>
              )}
            </dd>
          </div>
          
          <div>
            <dt className="text-sm font-medium text-gray-500 mb-1">Описание</dt>
            <dd className="text-sm text-gray-900">
              {caption || autoGeneratedCaption || (
                <span className="text-gray-400 italic">Не указано</span>
              )}
            </dd>
          </div>
        </dl>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg shadow p-6">
      <h2 className="text-lg font-semibold text-gray-900 mb-4">Редактирование метаданных</h2>
      
      <div className="space-y-4">
        {(autoGeneratedAlt || autoGeneratedTitle || autoGeneratedCaption) && (
          <button
            onClick={handleAutoFill}
            className="w-full flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-blue-700 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 transition-colors"
          >
            <Sparkles className="w-4 h-4" />
            Заполнить автоматически
          </button>
        )}

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Заголовок
            {autoGeneratedTitle && !formData.title && (
              <span className="ml-2 text-xs text-gray-400">(автогенерация)</span>
            )}
          </label>
          <Input
            type="text"
            value={formData.title}
            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
            placeholder={autoGeneratedTitle || "Заголовок файла"}
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Alt текст
            {autoGeneratedAlt && !formData.alt && (
              <span className="ml-2 text-xs text-gray-400">(автогенерация)</span>
            )}
          </label>
          <Input
            type="text"
            value={formData.alt}
            onChange={(e) => setFormData({ ...formData, alt: e.target.value })}
            placeholder={autoGeneratedAlt || "Описание для screen readers"}
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Описание
            {autoGeneratedCaption && !formData.caption && (
              <span className="ml-2 text-xs text-gray-400">(автогенерация)</span>
            )}
          </label>
          <Textarea
            value={formData.caption}
            onChange={(e) => setFormData({ ...formData, caption: e.target.value })}
            rows={3}
            placeholder={autoGeneratedCaption || "Подробное описание"}
          />
        </div>

        {error && (
          <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-sm text-red-800">{error}</p>
          </div>
        )}

        <div className="flex items-center gap-2">
          <button
            onClick={handleSave}
            disabled={isSaving}
            className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50"
          >
            <Check className="w-4 h-4" />
            {isSaving ? "Сохранение..." : "Сохранить"}
          </button>
          <button
            onClick={() => {
              setIsEditing(false);
              setError(null);
              setFormData({
                alt: alt || "",
                title: title || "",
                caption: caption || "",
              });
            }}
            disabled={isSaving}
            className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50"
          >
            <X className="w-4 h-4" />
            Отмена
          </button>
        </div>
      </div>
    </div>
  );
}
