"use client";

import { FileText, Image as ImageIcon } from "lucide-react";
import { formatBytes } from "@/lib/media/formatBytes";
import { resolveDisplayFilename } from "@/lib/media/resolveDisplayFilename";
import {
  mediaEntityTypeBadgeLabel,
  resolveAdminMediaListTitle,
} from "@/lib/media/mediaTitleOwnership";
import type { MediaAssetKind } from "@prisma/client";

interface MediaMetadataEditorLayoutProps {
  mediaId: string;
  media: {
    kind: MediaAssetKind;
    publicUrl: string | null;
    filename: string;
    originalName: string;
    mimeType: string;
    extension: string | null;
    sizeBytes: number;
    width?: number | null;
    height?: number | null;
  };
  metadata: {
    alt?: string | null;
    title?: string | null;
    caption?: string | null;
  };
  metadataWithSources: {
    alt: { value: string | undefined; source: "manual" | "auto" | "fallback" };
    title: { value: string | undefined; source: "manual" | "auto" | "fallback" };
    caption: { value: string | undefined; source: "manual" | "auto" | "fallback" };
  };
  autoGenerated: {
    alt?: string;
    title?: string;
    caption?: string;
  };
  usageContext?: {
    entityType: string;
    entityTitle?: string | null;
  } | null;
  onUpdate?: () => void;
}

/**
 * Preview + identity hierarchy for admin media detail.
 * Primary: MediaAsset.title (fallback entity title → canonical filename).
 * Secondary: canonical filename.
 * Technical: originalName as uploaded (never rewrite extension).
 */
export function MediaMetadataEditorLayout({
  media,
  mediaId,
  metadata,
  usageContext,
}: MediaMetadataEditorLayoutProps) {
  const displayFilename = resolveDisplayFilename({
    filename: media.filename,
    mimeType: media.mimeType,
    extension: media.extension,
  });
  const displayTitle = resolveAdminMediaListTitle({
    title: metadata.title,
    entityTitle: usageContext?.entityTitle,
    filename: displayFilename,
  });
  const entityBadge = mediaEntityTypeBadgeLabel(usageContext?.entityType);
  // originalName must render exactly as stored — do not run through mime-based extension rewrite.
  const originalNameAsUploaded = media.originalName;

  return (
    <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden">
      <div className="min-h-[500px] bg-gray-50 flex items-center justify-center p-8">
        {media.kind === "IMAGE" ? (
          <img
            src={`/api/media/${mediaId}`}
            alt={metadata.alt?.trim() || displayTitle}
            className="max-w-full max-h-[450px] object-contain rounded-lg"
          />
        ) : (
          <div className="w-64 h-64 flex items-center justify-center bg-gray-100 rounded-lg">
            <FileText className="w-24 h-24 text-gray-400" />
          </div>
        )}
      </div>

      <div className="p-6 border-t border-gray-200">
        <div className="flex items-start gap-4">
          <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center flex-shrink-0">
            {media.kind === "IMAGE" ? (
              <ImageIcon className="w-5 h-5 text-blue-600" />
            ) : (
              <FileText className="w-5 h-5 text-blue-600" />
            )}
          </div>
          <div className="flex-1 min-w-0 space-y-2">
            <div className="flex flex-wrap items-center gap-2 min-w-0">
              <p className="text-base font-semibold text-gray-900 truncate">{displayTitle}</p>
              {entityBadge && (
                <span className="inline-flex shrink-0 items-center px-2 py-0.5 rounded text-xs font-medium bg-slate-100 text-slate-700">
                  {entityBadge}
                </span>
              )}
            </div>
            <p className="text-sm text-gray-600 font-mono truncate" title={displayFilename}>
              {displayFilename}
            </p>
            <p className="text-xs text-gray-500">
              Исходный файл:{" "}
              <span className="font-mono break-all">{originalNameAsUploaded}</span>
            </p>
            <div className="pt-2 space-y-1">
              <p className="text-xs text-gray-500">
                {media.mimeType} • {formatBytes(media.sizeBytes)}
              </p>
              {media.width && media.height && (
                <p className="text-xs text-gray-500">
                  {media.width} × {media.height} px
                </p>
              )}
              {media.publicUrl && (
                <p className="text-xs text-gray-500 font-mono break-all">
                  Canonical URL: {media.publicUrl}
                </p>
              )}
            </div>
            {usageContext && (
              <div className="mt-3 pt-3 border-t border-gray-100">
                <p className="text-xs text-gray-500">Использование / сущность</p>
                <p className="text-sm font-medium text-gray-900 mt-1">
                  {entityBadge ?? usageContext.entityType}
                  {usageContext.entityTitle && `: ${usageContext.entityTitle}`}
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
