export const SEO_BASELINE = {
  migrationDate: "2026-08-24",
  migrationDateEvidence:
    "Accepted from the completed migration-date audit: public mamaGo 2.0 cutover on 2026-08-24.",
  method: "evergreen_yoy_median_adjusted",
  metric: "evergreen_clicks_weekly",
  urlClassRulesVersion: 1,
  computedAt: "2026-09-11T07:47:00.000Z",
  sourceProperty: "https://mamago.by/",
  dataRange: { start: "2025-05-10", end: "2026-09-07" },
  kWindow: { from: "2026-W20", to: "2026-W32" },
  yoyGrowthFactor: 1.1303,
  statisticUsed: "median",
  baselineByIsoWeek: {
    // W36 is retained as support for the first completed post-cutover gate measurement.
    "2026-W36": 1793,
    "2026-W37": 1543,
    "2026-W38": 1458,
    "2026-W39": 1476,
    "2026-W40": 1476,
    "2026-W41": 1493,
    "2026-W42": 1645,
    "2026-W43": 1645,
    "2026-W44": 1891,
    "2026-W45": 1891,
    "2026-W46": 1567,
    "2026-W47": 1391,
    "2026-W48": 1386,
    "2026-W49": 1266,
    "2026-W50": 1147,
    "2026-W51": 1087,
    "2026-W52": 1057,
    "2027-W01": 1645,
    "2027-W02": 1170,
    "2027-W03": 1170,
    "2027-W04": 1224,
    "2027-W05": 1249,
  },
  unavailableWeeks: ["2026-W53"],
  targetShare: 0.8,
  targetDate: "2026-11-01",
  targetIsoWeek: "2026-W44",
  measurementStartIsoWeek: "2026-W36",
  actualEvergreenByIsoWeek: {
    "2026-W36": 529,
  },
  confidence: "medium",
  confidenceReasons: [
    "Evergreen still contains ordinary seasonality: undated beaches, pools, parks and similar pages are intentionally classified as evergreen rather than calendar events.",
    "The pre-migration weakening from late July into early August 2026 remains unexplained even after the July event spike is removed.",
    "The long tail is classified deterministically by rules rather than manually reviewed URL by URL; the audited 63-row fixture protects the known high-value sample.",
  ],
  notes: [
    "The recovery gate metric is evergreen clicks, not total clicks. Total organic traffic includes calendar event traffic that returns independently of site recovery: roughly 700-900 event clicks per week through much of autumn 2025, rising to about 2,700 by late December.",
    "The unclear bucket is excluded from both evergreen and event series. Therefore evergreen_clicks_weekly means clicks from URLs classified evergreen by URL classification rules version 1, with event and unclear URLs excluded.",
    "Classification separates dated/calendar events from undated pages; it does not remove ordinary seasonality. Beaches, pools and parks remain evergreen. k=1.1303 was estimated from a May-August window with a high share of summer/outdoor interest and is applied to a November baseline with a different page mix. If the June evergreen uplift was driven mainly by seasonal pages, the November adjustment can be overstated.",
    "Re-check k in November 2026 against observed autumn evergreen traffic instead of extending the May-August adjustment by extrapolation. This is a planned validation, not a change to the current W44 gate.",
    "GSC Search Analytics dates are Pacific Time (America/Los_Angeles), not UTC or Europe/Minsk; deploy-event correlation can therefore shift by hours around a calendar boundary.",
    "Trailing/rolling statistics are measured after the historical window they summarize, so the measurement point is shifted later than the center of the contributing observations.",
    "Seasonal weekly baseline uses the median of the previous ISO year's same week number and its same-year neighbors (W-1, W, W+1), multiplied by k=1.1303 and rounded to whole weekly clicks for the gate configuration.",
    "2026-W53 has no 2025-W53 counterpart and is intentionally unavailable; no interpolation, nearest-week substitution or silent extrapolation is allowed.",
    "2026-W36 is included only to anchor the first completed post-cutover measurement and the linear on-track trajectory; the forward baseline schedule otherwise starts at current week 2026-W37.",
  ],
} as const;

export type SeoBaselineConfig = typeof SEO_BASELINE;
