-- Add BOOKING_STALE and BOOKING_NEEDS_ATTENTION to NotificationType enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_STALE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_NEEDS_ATTENTION';
